version: '3.8'

services:
  postgres:
    image: postgres:14.2-alpine
    ports:
      - 6543:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Pass@word
      - POSTGRES_DB=RecordStore
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - 2544:1433
    environment:
      SA_PASSWORD: Pass@word
      ACCEPT_EULA: Y
