// <auto-generated />
using System;
using EventSourcing.EF.Tests.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventSourcing.EF.Tests.SqlServer.Migrations
{
    [DbContext(typeof(SqlServerTestContext))]
    partial class SqlServerTestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EventSourcing.Core.Event<EventSourcing.Core.Tests.BankAccount>", b =>
                {
                    b.Property<Guid>("PartitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long?>("PreviousIndex")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasComputedColumnSql("CASE WHEN \"Index\" = 0 THEN NULL ELSE \"Index\" - 1 END", true);

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("ZeroIndex")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasComputedColumnSql("cast(0 as bigint)", true);

                    b.HasKey("PartitionId", "AggregateId", "Index");

                    b.HasIndex("AggregateType");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Type");

                    b.HasIndex("PartitionId", "AggregateId", "PreviousIndex");

                    b.ToTable("BankAccountEvents", (string)null);

                    b.HasDiscriminator<string>("Type").HasValue("Event<BankAccount>");

                    b.HasCheckConstraint("CK_BankAccountEvents_Discriminator", "[Type] IN (N'Event<BankAccount>', N'BankAccountCreatedEvent', N'BankAccountFundsDepositedEvent', N'BankAccountFundsTransferredEvent', N'BankAccountFundsWithdrawnEvent')");

                    b.HasCheckConstraint("CK_BankAccountEvents_NonNegativeIndex", "\"Index\" >= 0");
                });

            modelBuilder.Entity("EventSourcing.Core.Event<EventSourcing.Core.Tests.Mocks.EmptyAggregate>", b =>
                {
                    b.Property<Guid>("PartitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long?>("PreviousIndex")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasComputedColumnSql("CASE WHEN \"Index\" = 0 THEN NULL ELSE \"Index\" - 1 END", true);

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("ZeroIndex")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasComputedColumnSql("cast(0 as bigint)", true);

                    b.HasKey("PartitionId", "AggregateId", "Index");

                    b.HasIndex("AggregateType");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Type");

                    b.HasIndex("PartitionId", "AggregateId", "PreviousIndex");

                    b.ToTable("EmptyAggregateEvents", (string)null);

                    b.HasDiscriminator<string>("Type").HasValue("Event<EmptyAggregate>");

                    b.HasCheckConstraint("CK_EmptyAggregateEvents_Discriminator", "[Type] IN (N'Event<EmptyAggregate>', N'EmptyEvent')");

                    b.HasCheckConstraint("CK_EmptyAggregateEvents_NonNegativeIndex", "\"Index\" >= 0");
                });

            modelBuilder.Entity("EventSourcing.Core.Event<EventSourcing.Core.Tests.Mocks.MockAggregate>", b =>
                {
                    b.Property<Guid>("PartitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long?>("PreviousIndex")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasComputedColumnSql("CASE WHEN \"Index\" = 0 THEN NULL ELSE \"Index\" - 1 END", true);

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("ZeroIndex")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasComputedColumnSql("cast(0 as bigint)", true);

                    b.HasKey("PartitionId", "AggregateId", "Index");

                    b.HasIndex("AggregateType");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Type");

                    b.HasIndex("PartitionId", "AggregateId", "PreviousIndex");

                    b.ToTable("MockAggregateEvents", (string)null);

                    b.HasDiscriminator<string>("Type").HasValue("Event<MockAggregate>");

                    b.HasCheckConstraint("CK_MockAggregateEvents_Discriminator", "[Type] IN (N'Event<MockAggregate>', N'MockEvent')");

                    b.HasCheckConstraint("CK_MockAggregateEvents_NonNegativeIndex", "\"Index\" >= 0");
                });

            modelBuilder.Entity("EventSourcing.Core.Event<EventSourcing.Core.Tests.Mocks.SimpleAggregate>", b =>
                {
                    b.Property<Guid>("PartitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long?>("PreviousIndex")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasComputedColumnSql("CASE WHEN \"Index\" = 0 THEN NULL ELSE \"Index\" - 1 END", true);

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("ZeroIndex")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasComputedColumnSql("cast(0 as bigint)", true);

                    b.HasKey("PartitionId", "AggregateId", "Index");

                    b.HasIndex("AggregateType");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Type");

                    b.HasIndex("PartitionId", "AggregateId", "PreviousIndex");

                    b.ToTable("SimpleAggregateEvents", (string)null);

                    b.HasDiscriminator<string>("Type").HasValue("Event<SimpleAggregate>");

                    b.HasCheckConstraint("CK_SimpleAggregateEvents_Discriminator", "[Type] IN (N'Event<SimpleAggregate>', N'SimpleEvent')");

                    b.HasCheckConstraint("CK_SimpleAggregateEvents_NonNegativeIndex", "\"Index\" >= 0");
                });

            modelBuilder.Entity("EventSourcing.Core.Event<EventSourcing.Core.Tests.Mocks.SnapshotAggregate>", b =>
                {
                    b.Property<Guid>("PartitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long?>("PreviousIndex")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasComputedColumnSql("CASE WHEN \"Index\" = 0 THEN NULL ELSE \"Index\" - 1 END", true);

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("ZeroIndex")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasComputedColumnSql("cast(0 as bigint)", true);

                    b.HasKey("PartitionId", "AggregateId", "Index");

                    b.HasIndex("AggregateType");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Type");

                    b.HasIndex("PartitionId", "AggregateId", "PreviousIndex");

                    b.ToTable("SnapshotAggregateEvents", (string)null);

                    b.HasDiscriminator<string>("Type").HasValue("Event<SnapshotAggregate>");

                    b.HasCheckConstraint("CK_SnapshotAggregateEvents_Discriminator", "[Type] IN (N'Event<SnapshotAggregate>', N'SnapshotEvent')");

                    b.HasCheckConstraint("CK_SnapshotAggregateEvents_NonNegativeIndex", "\"Index\" >= 0");
                });

            modelBuilder.Entity("EventSourcing.Core.Snapshot<EventSourcing.Core.Tests.BankAccount>", b =>
                {
                    b.Property<Guid>("PartitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("PartitionId", "AggregateId", "Index");

                    b.HasIndex("AggregateType");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Type");

                    b.ToTable("BankAccountSnapshots", (string)null);

                    b.HasDiscriminator<string>("Type").HasValue("Snapshot<BankAccount>");

                    b.HasCheckConstraint("CK_BankAccountSnapshots_Discriminator", "[Type] IN (N'Snapshot<BankAccount>', N'BankAccountSnapshot')");

                    b.HasCheckConstraint("CK_BankAccountSnapshots_NonNegativeIndex", "\"Index\" >= 0");
                });

            modelBuilder.Entity("EventSourcing.Core.Snapshot<EventSourcing.Core.Tests.Mocks.EmptyAggregate>", b =>
                {
                    b.Property<Guid>("PartitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("PartitionId", "AggregateId", "Index");

                    b.HasIndex("AggregateType");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Type");

                    b.ToTable("EmptyAggregateSnapshots", (string)null);

                    b.HasDiscriminator<string>("Type").HasValue("Snapshot<EmptyAggregate>");

                    b.HasCheckConstraint("CK_EmptyAggregateSnapshots_Discriminator", "[Type] IN (N'Snapshot<EmptyAggregate>', N'EmptySnapshot')");

                    b.HasCheckConstraint("CK_EmptyAggregateSnapshots_NonNegativeIndex", "\"Index\" >= 0");
                });

            modelBuilder.Entity("EventSourcing.Core.Snapshot<EventSourcing.Core.Tests.Mocks.MockAggregate>", b =>
                {
                    b.Property<Guid>("PartitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("PartitionId", "AggregateId", "Index");

                    b.HasIndex("AggregateType");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Type");

                    b.ToTable("MockAggregateSnapshots", (string)null);

                    b.HasDiscriminator<string>("Type").HasValue("Snapshot<MockAggregate>");

                    b.HasCheckConstraint("CK_MockAggregateSnapshots_Discriminator", "[Type] IN (N'Snapshot<MockAggregate>', N'MockSnapshot')");

                    b.HasCheckConstraint("CK_MockAggregateSnapshots_NonNegativeIndex", "\"Index\" >= 0");
                });

            modelBuilder.Entity("EventSourcing.Core.Snapshot<EventSourcing.Core.Tests.Mocks.SimpleAggregate>", b =>
                {
                    b.Property<Guid>("PartitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("PartitionId", "AggregateId", "Index");

                    b.HasIndex("AggregateType");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Type");

                    b.ToTable("SimpleAggregateSnapshots", (string)null);

                    b.HasCheckConstraint("CK_SimpleAggregateSnapshots_NonNegativeIndex", "\"Index\" >= 0");
                });

            modelBuilder.Entity("EventSourcing.Core.Snapshot<EventSourcing.Core.Tests.Mocks.SnapshotAggregate>", b =>
                {
                    b.Property<Guid>("PartitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("PartitionId", "AggregateId", "Index");

                    b.HasIndex("AggregateType");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Type");

                    b.ToTable("SnapshotAggregateSnapshots", (string)null);

                    b.HasDiscriminator<string>("Type").HasValue("Snapshot<SnapshotAggregate>");

                    b.HasCheckConstraint("CK_SnapshotAggregateSnapshots_Discriminator", "[Type] IN (N'Snapshot<SnapshotAggregate>', N'SnapshotSnapshot')");

                    b.HasCheckConstraint("CK_SnapshotAggregateSnapshots_NonNegativeIndex", "\"Index\" >= 0");
                });

            modelBuilder.Entity("EventSourcing.Core.Tests.BankAccountProjection", b =>
                {
                    b.Property<Guid>("PartitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FactoryType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("PartitionId", "AggregateId");

                    b.HasIndex("AggregateType");

                    b.HasIndex("Hash");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Type");

                    b.ToTable("BankAccountProjection");
                });

            modelBuilder.Entity("EventSourcing.Core.Tests.Mocks.EmptyProjection", b =>
                {
                    b.Property<Guid>("PartitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FactoryType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("PartitionId", "AggregateId");

                    b.HasIndex("AggregateType");

                    b.HasIndex("Hash");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Type");

                    b.ToTable("EmptyProjection");
                });

            modelBuilder.Entity("EventSourcing.Core.Tests.Mocks.MockAggregateProjection", b =>
                {
                    b.Property<Guid>("PartitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FactoryType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("MockBoolean")
                        .HasColumnType("bit");

                    b.Property<decimal>("MockDecimal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("MockDouble")
                        .HasColumnType("float");

                    b.Property<int>("MockEnum")
                        .HasColumnType("int");

                    b.Property<byte>("MockFlagEnum")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("MockFloatList")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<double?>("MockNullableDouble")
                        .HasColumnType("float");

                    b.Property<string>("MockNullableString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MockString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MockStringSet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("PartitionId", "AggregateId");

                    b.HasIndex("AggregateType");

                    b.HasIndex("Hash");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Type");

                    b.ToTable("MockAggregateProjection");

                    b.HasCheckConstraint("CK_MockAggregateProjection_MockEnum_Enum", "[MockEnum] IN (0, 1, 2)");
                });

            modelBuilder.Entity("EventSourcing.Core.Tests.BankAccountCreatedEvent", b =>
                {
                    b.HasBaseType("EventSourcing.Core.Event<EventSourcing.Core.Tests.BankAccount>");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("BankAccountCreatedEvent");

                    b.HasCheckConstraint("CK_BankAccountEvents_Discriminator", "[Type] IN (N'Event<BankAccount>', N'BankAccountCreatedEvent', N'BankAccountFundsDepositedEvent', N'BankAccountFundsTransferredEvent', N'BankAccountFundsWithdrawnEvent')");

                    b.HasCheckConstraint("CK_BankAccountEvents_NonNegativeIndex", "\"Index\" >= 0");

                    b.HasCheckConstraint("CK_BankAccountCreatedEvent_NotNull", "NOT \"Type\" = 'BankAccountCreatedEvent' OR (\"Name\" IS NOT NULL AND \"Iban\" IS NOT NULL)");
                });

            modelBuilder.Entity("EventSourcing.Core.Tests.BankAccountFundsDepositedEvent", b =>
                {
                    b.HasBaseType("EventSourcing.Core.Event<EventSourcing.Core.Tests.BankAccount>");

                    b.Property<decimal>("Amount")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("BankAccountFundsDepositedEvent");

                    b.HasCheckConstraint("CK_BankAccountEvents_Discriminator", "[Type] IN (N'Event<BankAccount>', N'BankAccountCreatedEvent', N'BankAccountFundsDepositedEvent', N'BankAccountFundsTransferredEvent', N'BankAccountFundsWithdrawnEvent')");

                    b.HasCheckConstraint("CK_BankAccountEvents_NonNegativeIndex", "\"Index\" >= 0");

                    b.HasCheckConstraint("CK_BankAccountFundsDepositedEvent_NotNull", "NOT \"Type\" = 'BankAccountFundsDepositedEvent' OR (\"Amount\" IS NOT NULL)");
                });

            modelBuilder.Entity("EventSourcing.Core.Tests.BankAccountFundsTransferredEvent", b =>
                {
                    b.HasBaseType("EventSourcing.Core.Event<EventSourcing.Core.Tests.BankAccount>");

                    b.Property<decimal>("Amount")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CreditorAccount")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DebtorAccount")
                        .HasColumnType("uniqueidentifier");

                    b.HasDiscriminator().HasValue("BankAccountFundsTransferredEvent");

                    b.HasCheckConstraint("CK_BankAccountEvents_Discriminator", "[Type] IN (N'Event<BankAccount>', N'BankAccountCreatedEvent', N'BankAccountFundsDepositedEvent', N'BankAccountFundsTransferredEvent', N'BankAccountFundsWithdrawnEvent')");

                    b.HasCheckConstraint("CK_BankAccountEvents_NonNegativeIndex", "\"Index\" >= 0");

                    b.HasCheckConstraint("CK_BankAccountFundsTransferredEvent_NotNull", "NOT \"Type\" = 'BankAccountFundsTransferredEvent' OR (\"DebtorAccount\" IS NOT NULL AND \"CreditorAccount\" IS NOT NULL AND \"Amount\" IS NOT NULL)");
                });

            modelBuilder.Entity("EventSourcing.Core.Tests.BankAccountFundsWithdrawnEvent", b =>
                {
                    b.HasBaseType("EventSourcing.Core.Event<EventSourcing.Core.Tests.BankAccount>");

                    b.Property<decimal>("Amount")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("BankAccountFundsWithdrawnEvent");

                    b.HasCheckConstraint("CK_BankAccountEvents_Discriminator", "[Type] IN (N'Event<BankAccount>', N'BankAccountCreatedEvent', N'BankAccountFundsDepositedEvent', N'BankAccountFundsTransferredEvent', N'BankAccountFundsWithdrawnEvent')");

                    b.HasCheckConstraint("CK_BankAccountEvents_NonNegativeIndex", "\"Index\" >= 0");

                    b.HasCheckConstraint("CK_BankAccountFundsWithdrawnEvent_NotNull", "NOT \"Type\" = 'BankAccountFundsWithdrawnEvent' OR (\"Amount\" IS NOT NULL)");
                });

            modelBuilder.Entity("EventSourcing.Core.Tests.BankAccountSnapshot", b =>
                {
                    b.HasBaseType("EventSourcing.Core.Snapshot<EventSourcing.Core.Tests.BankAccount>");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("BankAccountSnapshot");

                    b.HasCheckConstraint("CK_BankAccountSnapshots_Discriminator", "[Type] IN (N'Snapshot<BankAccount>', N'BankAccountSnapshot')");

                    b.HasCheckConstraint("CK_BankAccountSnapshots_NonNegativeIndex", "\"Index\" >= 0");

                    b.HasCheckConstraint("CK_BankAccountSnapshot_NotNull", "NOT \"Type\" = 'BankAccountSnapshot' OR (\"Name\" IS NOT NULL AND \"Iban\" IS NOT NULL AND \"Balance\" IS NOT NULL)");
                });

            modelBuilder.Entity("EventSourcing.Core.Tests.Mocks.EmptyEvent", b =>
                {
                    b.HasBaseType("EventSourcing.Core.Event<EventSourcing.Core.Tests.Mocks.EmptyAggregate>");

                    b.HasDiscriminator().HasValue("EmptyEvent");

                    b.HasCheckConstraint("CK_EmptyAggregateEvents_Discriminator", "[Type] IN (N'Event<EmptyAggregate>', N'EmptyEvent')");

                    b.HasCheckConstraint("CK_EmptyAggregateEvents_NonNegativeIndex", "\"Index\" >= 0");
                });

            modelBuilder.Entity("EventSourcing.Core.Tests.Mocks.EmptySnapshot", b =>
                {
                    b.HasBaseType("EventSourcing.Core.Snapshot<EventSourcing.Core.Tests.Mocks.EmptyAggregate>");

                    b.HasDiscriminator().HasValue("EmptySnapshot");

                    b.HasCheckConstraint("CK_EmptyAggregateSnapshots_Discriminator", "[Type] IN (N'Snapshot<EmptyAggregate>', N'EmptySnapshot')");

                    b.HasCheckConstraint("CK_EmptyAggregateSnapshots_NonNegativeIndex", "\"Index\" >= 0");
                });

            modelBuilder.Entity("EventSourcing.Core.Tests.Mocks.MockEvent", b =>
                {
                    b.HasBaseType("EventSourcing.Core.Event<EventSourcing.Core.Tests.Mocks.MockAggregate>");

                    b.Property<bool>("MockBoolean")
                        .HasColumnType("bit");

                    b.Property<decimal>("MockDecimal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("MockDouble")
                        .HasColumnType("float");

                    b.Property<int>("MockEnum")
                        .HasColumnType("int");

                    b.Property<byte>("MockFlagEnum")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("MockFloatList")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<double?>("MockNullableDouble")
                        .HasColumnType("float");

                    b.Property<string>("MockNullableString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MockString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MockStringSet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("MockEvent");

                    b.HasCheckConstraint("CK_MockAggregateEvents_Discriminator", "[Type] IN (N'Event<MockAggregate>', N'MockEvent')");

                    b.HasCheckConstraint("CK_MockAggregateEvents_NonNegativeIndex", "\"Index\" >= 0");

                    b.HasCheckConstraint("CK_MockAggregateEvents_MockEnum_Enum", "[MockEnum] IN (0, 1, 2)");

                    b.HasCheckConstraint("CK_MockEvent_NotNull", "NOT \"Type\" = 'MockEvent' OR (\"MockBoolean\" IS NOT NULL AND \"MockString\" IS NOT NULL AND \"MockDecimal\" IS NOT NULL AND \"MockDouble\" IS NOT NULL AND \"MockEnum\" IS NOT NULL AND \"MockFlagEnum\" IS NOT NULL AND \"MockFloatList\" IS NOT NULL AND \"MockStringSet\" IS NOT NULL)");
                });

            modelBuilder.Entity("EventSourcing.Core.Tests.Mocks.MockSnapshot", b =>
                {
                    b.HasBaseType("EventSourcing.Core.Snapshot<EventSourcing.Core.Tests.Mocks.MockAggregate>");

                    b.Property<bool>("MockBoolean")
                        .HasColumnType("bit");

                    b.Property<decimal>("MockDecimal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("MockDouble")
                        .HasColumnType("float");

                    b.Property<int>("MockEnum")
                        .HasColumnType("int");

                    b.Property<byte>("MockFlagEnum")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("MockFloatList")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<double?>("MockNullableDouble")
                        .HasColumnType("float");

                    b.Property<string>("MockNullableString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MockString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MockStringSet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("MockSnapshot");

                    b.HasCheckConstraint("CK_MockAggregateSnapshots_Discriminator", "[Type] IN (N'Snapshot<MockAggregate>', N'MockSnapshot')");

                    b.HasCheckConstraint("CK_MockAggregateSnapshots_NonNegativeIndex", "\"Index\" >= 0");

                    b.HasCheckConstraint("CK_MockAggregateSnapshots_MockEnum_Enum", "[MockEnum] IN (0, 1, 2)");

                    b.HasCheckConstraint("CK_MockSnapshot_NotNull", "NOT \"Type\" = 'MockSnapshot' OR (\"MockBoolean\" IS NOT NULL AND \"MockString\" IS NOT NULL AND \"MockDecimal\" IS NOT NULL AND \"MockDouble\" IS NOT NULL AND \"MockEnum\" IS NOT NULL AND \"MockFlagEnum\" IS NOT NULL AND \"MockFloatList\" IS NOT NULL AND \"MockStringSet\" IS NOT NULL)");
                });

            modelBuilder.Entity("EventSourcing.Core.Tests.Mocks.SimpleEvent", b =>
                {
                    b.HasBaseType("EventSourcing.Core.Event<EventSourcing.Core.Tests.Mocks.SimpleAggregate>");

                    b.HasDiscriminator().HasValue("SimpleEvent");

                    b.HasCheckConstraint("CK_SimpleAggregateEvents_Discriminator", "[Type] IN (N'Event<SimpleAggregate>', N'SimpleEvent')");

                    b.HasCheckConstraint("CK_SimpleAggregateEvents_NonNegativeIndex", "\"Index\" >= 0");
                });

            modelBuilder.Entity("EventSourcing.Core.Tests.Mocks.SnapshotEvent", b =>
                {
                    b.HasBaseType("EventSourcing.Core.Event<EventSourcing.Core.Tests.Mocks.SnapshotAggregate>");

                    b.HasDiscriminator().HasValue("SnapshotEvent");

                    b.HasCheckConstraint("CK_SnapshotAggregateEvents_Discriminator", "[Type] IN (N'Event<SnapshotAggregate>', N'SnapshotEvent')");

                    b.HasCheckConstraint("CK_SnapshotAggregateEvents_NonNegativeIndex", "\"Index\" >= 0");
                });

            modelBuilder.Entity("EventSourcing.Core.Tests.Mocks.SnapshotSnapshot", b =>
                {
                    b.HasBaseType("EventSourcing.Core.Snapshot<EventSourcing.Core.Tests.Mocks.SnapshotAggregate>");

                    b.Property<int>("Counter")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("SnapshotSnapshot");

                    b.HasCheckConstraint("CK_SnapshotAggregateSnapshots_Discriminator", "[Type] IN (N'Snapshot<SnapshotAggregate>', N'SnapshotSnapshot')");

                    b.HasCheckConstraint("CK_SnapshotAggregateSnapshots_NonNegativeIndex", "\"Index\" >= 0");

                    b.HasCheckConstraint("CK_SnapshotSnapshot_NotNull", "NOT \"Type\" = 'SnapshotSnapshot' OR (\"Counter\" IS NOT NULL)");
                });

            modelBuilder.Entity("EventSourcing.Core.Event<EventSourcing.Core.Tests.BankAccount>", b =>
                {
                    b.HasOne("EventSourcing.Core.Event<EventSourcing.Core.Tests.BankAccount>", null)
                        .WithOne()
                        .HasForeignKey("EventSourcing.Core.Event<EventSourcing.Core.Tests.BankAccount>", "PartitionId", "AggregateId", "PreviousIndex")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_BankAccountEvents_ConsecutiveIndex");
                });

            modelBuilder.Entity("EventSourcing.Core.Event<EventSourcing.Core.Tests.Mocks.EmptyAggregate>", b =>
                {
                    b.HasOne("EventSourcing.Core.Event<EventSourcing.Core.Tests.Mocks.EmptyAggregate>", null)
                        .WithOne()
                        .HasForeignKey("EventSourcing.Core.Event<EventSourcing.Core.Tests.Mocks.EmptyAggregate>", "PartitionId", "AggregateId", "PreviousIndex")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_EmptyAggregateEvents_ConsecutiveIndex");
                });

            modelBuilder.Entity("EventSourcing.Core.Event<EventSourcing.Core.Tests.Mocks.MockAggregate>", b =>
                {
                    b.HasOne("EventSourcing.Core.Event<EventSourcing.Core.Tests.Mocks.MockAggregate>", null)
                        .WithOne()
                        .HasForeignKey("EventSourcing.Core.Event<EventSourcing.Core.Tests.Mocks.MockAggregate>", "PartitionId", "AggregateId", "PreviousIndex")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_MockAggregateEvents_ConsecutiveIndex");
                });

            modelBuilder.Entity("EventSourcing.Core.Event<EventSourcing.Core.Tests.Mocks.SimpleAggregate>", b =>
                {
                    b.HasOne("EventSourcing.Core.Event<EventSourcing.Core.Tests.Mocks.SimpleAggregate>", null)
                        .WithOne()
                        .HasForeignKey("EventSourcing.Core.Event<EventSourcing.Core.Tests.Mocks.SimpleAggregate>", "PartitionId", "AggregateId", "PreviousIndex")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_SimpleAggregateEvents_ConsecutiveIndex");
                });

            modelBuilder.Entity("EventSourcing.Core.Event<EventSourcing.Core.Tests.Mocks.SnapshotAggregate>", b =>
                {
                    b.HasOne("EventSourcing.Core.Event<EventSourcing.Core.Tests.Mocks.SnapshotAggregate>", null)
                        .WithOne()
                        .HasForeignKey("EventSourcing.Core.Event<EventSourcing.Core.Tests.Mocks.SnapshotAggregate>", "PartitionId", "AggregateId", "PreviousIndex")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_SnapshotAggregateEvents_ConsecutiveIndex");
                });

            modelBuilder.Entity("EventSourcing.Core.Snapshot<EventSourcing.Core.Tests.BankAccount>", b =>
                {
                    b.HasOne("EventSourcing.Core.Event<EventSourcing.Core.Tests.BankAccount>", null)
                        .WithOne()
                        .HasForeignKey("EventSourcing.Core.Snapshot<EventSourcing.Core.Tests.BankAccount>", "PartitionId", "AggregateId", "Index")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventSourcing.Core.Snapshot<EventSourcing.Core.Tests.Mocks.EmptyAggregate>", b =>
                {
                    b.HasOne("EventSourcing.Core.Event<EventSourcing.Core.Tests.Mocks.EmptyAggregate>", null)
                        .WithOne()
                        .HasForeignKey("EventSourcing.Core.Snapshot<EventSourcing.Core.Tests.Mocks.EmptyAggregate>", "PartitionId", "AggregateId", "Index")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventSourcing.Core.Snapshot<EventSourcing.Core.Tests.Mocks.MockAggregate>", b =>
                {
                    b.HasOne("EventSourcing.Core.Event<EventSourcing.Core.Tests.Mocks.MockAggregate>", null)
                        .WithOne()
                        .HasForeignKey("EventSourcing.Core.Snapshot<EventSourcing.Core.Tests.Mocks.MockAggregate>", "PartitionId", "AggregateId", "Index")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventSourcing.Core.Snapshot<EventSourcing.Core.Tests.Mocks.SimpleAggregate>", b =>
                {
                    b.HasOne("EventSourcing.Core.Event<EventSourcing.Core.Tests.Mocks.SimpleAggregate>", null)
                        .WithOne()
                        .HasForeignKey("EventSourcing.Core.Snapshot<EventSourcing.Core.Tests.Mocks.SimpleAggregate>", "PartitionId", "AggregateId", "Index")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventSourcing.Core.Snapshot<EventSourcing.Core.Tests.Mocks.SnapshotAggregate>", b =>
                {
                    b.HasOne("EventSourcing.Core.Event<EventSourcing.Core.Tests.Mocks.SnapshotAggregate>", null)
                        .WithOne()
                        .HasForeignKey("EventSourcing.Core.Snapshot<EventSourcing.Core.Tests.Mocks.SnapshotAggregate>", "PartitionId", "AggregateId", "Index")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventSourcing.Core.Tests.Mocks.MockAggregateProjection", b =>
                {
                    b.OwnsOne("EventSourcing.Core.Tests.Mocks.MockNestedRecord", "MockNestedRecord", b1 =>
                        {
                            b1.Property<Guid>("MockAggregateProjectionPartitionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("MockAggregateProjectionAggregateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("MockBoolean")
                                .HasColumnType("bit");

                            b1.Property<decimal>("MockDecimal")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<double>("MockDouble")
                                .HasColumnType("float");

                            b1.Property<string>("MockString")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("MockAggregateProjectionPartitionId", "MockAggregateProjectionAggregateId");

                            b1.ToTable("MockAggregateProjection");

                            b1.WithOwner()
                                .HasForeignKey("MockAggregateProjectionPartitionId", "MockAggregateProjectionAggregateId");
                        });

                    b.OwnsMany("EventSourcing.Core.Tests.Mocks.MockNestedRecordItem", "MockNestedRecordList", b1 =>
                        {
                            b1.Property<Guid>("MockAggregateProjectionPartitionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("MockAggregateProjectionAggregateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"), 1L, 1);

                            b1.Property<bool>("MockBoolean")
                                .HasColumnType("bit");

                            b1.Property<decimal>("MockDecimal")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<double>("MockDouble")
                                .HasColumnType("float");

                            b1.Property<string>("MockString")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("MockAggregateProjectionPartitionId", "MockAggregateProjectionAggregateId", "Id");

                            b1.ToTable("MockAggregateProjection_MockNestedRecordList");

                            b1.WithOwner()
                                .HasForeignKey("MockAggregateProjectionPartitionId", "MockAggregateProjectionAggregateId");
                        });

                    b.Navigation("MockNestedRecord")
                        .IsRequired();

                    b.Navigation("MockNestedRecordList");
                });

            modelBuilder.Entity("EventSourcing.Core.Tests.Mocks.MockEvent", b =>
                {
                    b.OwnsOne("EventSourcing.Core.Tests.Mocks.MockNestedRecord", "MockNestedRecord", b1 =>
                        {
                            b1.Property<Guid>("MockEventPartitionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("MockEventAggregateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<long>("MockEventIndex")
                                .HasColumnType("bigint");

                            b1.Property<bool>("MockBoolean")
                                .HasColumnType("bit");

                            b1.Property<decimal>("MockDecimal")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<double>("MockDouble")
                                .HasColumnType("float");

                            b1.Property<string>("MockString")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("MockEventPartitionId", "MockEventAggregateId", "MockEventIndex");

                            b1.ToTable("MockAggregateEvents");

                            b1.WithOwner()
                                .HasForeignKey("MockEventPartitionId", "MockEventAggregateId", "MockEventIndex");
                        });

                    b.OwnsMany("EventSourcing.Core.Tests.Mocks.MockNestedRecordItem", "MockNestedRecordList", b1 =>
                        {
                            b1.Property<Guid>("MockEventPartitionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("MockEventAggregateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<long>("MockEventIndex")
                                .HasColumnType("bigint");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"), 1L, 1);

                            b1.Property<bool>("MockBoolean")
                                .HasColumnType("bit");

                            b1.Property<decimal>("MockDecimal")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<double>("MockDouble")
                                .HasColumnType("float");

                            b1.Property<string>("MockString")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("MockEventPartitionId", "MockEventAggregateId", "MockEventIndex", "Id");

                            b1.ToTable("MockAggregateEvents_MockNestedRecordList");

                            b1.WithOwner()
                                .HasForeignKey("MockEventPartitionId", "MockEventAggregateId", "MockEventIndex");
                        });

                    b.Navigation("MockNestedRecord")
                        .IsRequired();

                    b.Navigation("MockNestedRecordList");
                });

            modelBuilder.Entity("EventSourcing.Core.Tests.Mocks.MockSnapshot", b =>
                {
                    b.OwnsOne("EventSourcing.Core.Tests.Mocks.MockNestedRecord", "MockNestedRecord", b1 =>
                        {
                            b1.Property<Guid>("MockSnapshotPartitionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("MockSnapshotAggregateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<long>("MockSnapshotIndex")
                                .HasColumnType("bigint");

                            b1.Property<bool>("MockBoolean")
                                .HasColumnType("bit");

                            b1.Property<decimal>("MockDecimal")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<double>("MockDouble")
                                .HasColumnType("float");

                            b1.Property<string>("MockString")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("MockSnapshotPartitionId", "MockSnapshotAggregateId", "MockSnapshotIndex");

                            b1.ToTable("MockAggregateSnapshots");

                            b1.WithOwner()
                                .HasForeignKey("MockSnapshotPartitionId", "MockSnapshotAggregateId", "MockSnapshotIndex");
                        });

                    b.OwnsMany("EventSourcing.Core.Tests.Mocks.MockNestedRecordItem", "MockNestedRecordList", b1 =>
                        {
                            b1.Property<Guid>("MockSnapshotPartitionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("MockSnapshotAggregateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<long>("MockSnapshotIndex")
                                .HasColumnType("bigint");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"), 1L, 1);

                            b1.Property<bool>("MockBoolean")
                                .HasColumnType("bit");

                            b1.Property<decimal>("MockDecimal")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<double>("MockDouble")
                                .HasColumnType("float");

                            b1.Property<string>("MockString")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("MockSnapshotPartitionId", "MockSnapshotAggregateId", "MockSnapshotIndex", "Id");

                            b1.ToTable("MockAggregateSnapshots_MockNestedRecordList");

                            b1.WithOwner()
                                .HasForeignKey("MockSnapshotPartitionId", "MockSnapshotAggregateId", "MockSnapshotIndex");
                        });

                    b.Navigation("MockNestedRecord")
                        .IsRequired();

                    b.Navigation("MockNestedRecordList");
                });
#pragma warning restore 612, 618
        }
    }
}
