version: '3.8'

services:
  database:
    image: postgres:14.2-alpine
    ports:
      - 6543:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Pass@word
      - POSTGRES_DB=RecordStore
