name: .NET Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14.2-alpine
        ports:
          - 6543:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Pass@word
          POSTGRES_DB: RecordStore
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: Pass@word # You should set this to a secrete and reference it here
        ports:
          - 2544:1433

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Update EF Core Databases
      run: |
        dotnet tool install --global dotnet-ef
        dotnet tool restore
        
        dotnet ef migrations add AddInitialMigration -p EventSourcing.EF.Tests.Postgres
        dotnet ef database update -p EventSourcing.EF.Tests.Postgres
        
        dotnet ef migrations add AddInitialMigration -p EventSourcing.EF.Tests.SqlServer
        dotnet ef database update -p EventSourcing.EF.Tests.SqlServer
        
        dotnet ef database update -p EventSourcing.Example
      env:
        ASPNETCORE_ENVIRONMENT: Development

    - name: Test
      run: dotnet test --no-build --verbosity normal
      env:
        Cosmos__ConnectionString: ${{ secrets.COSMOS_CONNECTIONSTRING }}
        Cosmos__Database: ${{ secrets.COSMOS_DATABASE }}
        Cosmos__Container: ${{ secrets.COSMOS_CONTAINER }}