name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --logger trx --results-directory "TestResults"
      env:
        Cosmos__ConnectionString: ${{ secrets.COSMOS_CONNECTIONSTRING }}
        Cosmos__Database: ${{ secrets.COSMOS_DATABASE }}
        Cosmos__Container: ${{ secrets.COSMOS_CONTAINER }}
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v2
      with:
        name: dotnet-results
        path: TestResults
      if: ${{ always() }}
